title: IsTensor
description: 一道精致的灰
url: https://istensor.github.io
avatar: /assets/img/avatar.jpg
paginate: 5
permalink: pretty
cover_image: /assets/img/cover.jpeg
timezone: +0000

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      author: "Ethan Wang"
      image: "assets/img/avatar.jpg"
      share: true
  - scope:
      path: ""      
      type: "pages"
    values:
      layout: "page"
      author: "Ethan Wang"
      image: "assets/img/avatar.jpg"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

include:
  - _pages
  
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts/

# Optimize Jekyl SEO Tag
twitter:
  username: istensor
  card: summary
logo: logo.png
social:
  name: Ethan Wang
  links:
    # - https://twitter.com/vszhub
    - https://github.com/isTensor
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: UA-179353572-1


# Specify the author for blog posts
author:
  name: Ethan Wang
  url: https://github.com/isTensor/
  email: istensor@gmail.com

remote_theme: vszhub/not-pure-poole
